### PR TITLE
upstream-dev CI

### LINKED ISSUE #18: Add upstream-dev CI
Would be nice to have this for git tip versions of xarray, dask, pint (maybe more?)

### PR DESCRIPTION
**Pull request by keewis**
This adds a upstream-dev CI.

- [x] closes #18

### CODE REVIEW

**Comment by keewis** [comment]
the CI seems to work, so this should be ready for review and merge. I'd especially take a look at the upstream-dev dependencies: should we add more, like the main indirect dependencies of xarray (pandas, mostly).

**Comment by jthielen** [comment]
Do we want to have this CI job be optional or not (i.e., should an upstream but unreleased break hold up PRs here until it is fixed)? Though, that may require it to be a separate check (which I'm not sure on what the status of separate checks is from https://github.com/xarray-contrib/pint-xarray/pull/16).

**Comment by keewis** [comment]
we currently don't have branch protection on, so I'd say if the fix wouldn't take too long it's fine to merge with a failing upstream-dev CI. If it's not clear how to fix that (even upstream) we should just add conditional xfails.

**Comment by jthielen** [comment]
@keewis Sounds good. Hopefully the separate checks can get figured out at some point. I think then this should be good to merge.

**Pull request merged**
